#!/bin/bash
#
#PBS -S /bin/bash
#PBS -N drkostas_kmeans_tcga_distributed_nodes2ppn10
#PBS -M default@mail
#PBS -m abe
#PBS -A ACF-UTK0150
#PBS -o /lustre/haven/proj/UTK0150/kgeorgio/playground/logs/kmeans_tcga_distributed_nodes2ppn10_$PBS_JOBID.o
#PBS -e /lustre/haven/proj/UTK0150/kgeorgio/playground/logs/kmeans_tcga_distributed_nodes2ppn10_$PBS_JOBID.e
#PBS -l nodes=2:ppn=10 # ppn=process per node
#PBS -l pmem=4gb # memory per node
#PBS -l walltime=00:05:00
#PBS -l qos=condo

# Print commands and their arguments in a sequential order
set -x

##
## Job Code
##

# CD to the class lustre project directory
cd /lustre/haven/proj/UTK0150/$USER/assignment2
# Run assignment2.py with the appropriate arguments
CONDA_BIN="~/anaconda3/envs/dse512_playground/bin/"
conf="/lustre/haven/proj/UTK0150/${USER}/playground/confs/assignment2_isaac_tcga_nodes2ppn10.yml"
log="/lustre/haven/proj/UTK0150/${USER}/playground/logs/assignment2_isaac_tcga_nodes2ppn10.log"
command="${CONDA_BIN}python assignment2.py -c ${conf} -l ${log}"
eval $command

qstat -f $PBS_JOBID

