tag: all  # required_only or all
non_parallel:
  - properties:
      num_processes:
        - 1
      epochs: 3
      batch_size_train: 128
      batch_size_test: 1000
      learning_rate: 0.01
      momentum: 0.5
      test_before_train: true
      dataset:
        name: mnist
        save_path: ../data/mnist
    type: optional  # required or optional
    enabled: false  # true or false
data_parallel:
  - properties:
      num_processes:
#        - 1
        - 2
        - 4
#        - 8
      epochs: 6
      batch_size_train: 32
      batch_size_test: 1000
      learning_rate: 0.01
      momentum: 0.5
      test_before_train: true
      dataset:
        name: mnist
        save_path: ../data/mnist
    type: required  # required or optional
    enabled: true  # true or false