tag: all  # required_only or all
non_parallel:
  - properties:
      num_processes:
        - 1
        - 2
#        - 4
#        - 8
      epochs: 3
      batch_size_train: 64
      batch_size_test: 1000
      learning_rate: 0.01
      momentum: 0.5
      test_before_train: false
      dataset:
        name: mnist
        save_path: ../data/mnist
    type: required  # required or optional
    enabled: true  # true or false